

def create_bibliography(id_frame, out_fp):
    '''
    :param id_frame: pandas df as generated by get_PMIDS
    :param out_fp: output file path
    :return: None // Writes text file with lib content in out_fp dir
    '''

    # creating lib
    lib = str()

    for idx, row in id_frame.drop_duplicates(subset=['label']).iterrows():
        lib += f'[{row["label"]}] {row["Citation"]}\n'

    # create a Bibliography file
    lib_file = open(out_fp,'w')
    lib_file.write(lib)
    lib_file.close()