import copy

def update_text(text, id_frame, out_FP, custom_RegX=None):
    '''
    :param text: input text
    :param id_frame: pandas df as generated by get_PMIDS
    :param out_FP: str.: output file path
    :return: None // Writes text file with reformatted text content in out_fp dir
    '''


    # updating text with references
    updated_text = copy.deepcopy(text)

    if not custom_RegX:
        for idx, row in id_frame.iterrows():
            updated_text = updated_text.replace('pmid:'+row['PMID'], str(row['label'])).replace\
                ('pmid: '+row['PMID'], str(row['label'])).replace('pmid'+row['PMID'], str(row['label']))\
                .replace('PMID:'+row['PMID'], str(row['label'])).replace('PMID: '+row['PMID'], str(row['label'])) \
                .replace('PMID'+row['PMID'], str(row['label']))

    else:
        for idx, row in id_frame.iterrows():
            updated_text = updated_text.replace(custom_RegX+row['PMID'], str(row['label']))


    # create file with edited text
    text_file = open(out_FP,'w')
    text_file.write(updated_text)
    text_file.close()

    return None
